GOOGLE_APPLICATION_CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS"
FIREBASE_ADMIN_CREDENTIALS = "FIREBASE_ADMIN_CREDENTIALS"
FIREBASE_URL = "FIREBASE_URL"
BIGQUERY_DATASET = "BIGQUERY_DATASET"
BIGQUERY_LOCATION = "BIGQUERY_LOCATION"
BIGQUERY_TABLE_NAME = "BIGQUERY_TABLE_NAME"
BIGQUERY_INTERMEDIATE_TABLE_NAME = "BIGQUERY_INTERMEDIATE_TABLE_NAME"

GCP_APPLICATION_CREDENTIALS = (
    GOOGLE_APPLICATION_CREDENTIALS,
    FIREBASE_ADMIN_CREDENTIALS,
)

PRODUCTION_ENV_VARS = (
    BIGQUERY_LOCATION,
    BIGQUERY_DATASET,
    BIGQUERY_TABLE_NAME,
    BIGQUERY_INTERMEDIATE_TABLE_NAME,
    FIREBASE_URL,
)

DOWNLOAD = "download"
UPDATE_SEQUENCE = "update_sequence"
COMBINE_TRADES = "combine_trades"
CALCULATE_COLUMNS = "calculate_columns"

STEPS = [
    DOWNLOAD,
    UPDATE_SEQUENCE,
    COMBINE_TRADES,
    CALCULATE_COLUMNS,
]

BITMEX_S3 = "https://s3-eu-west-1.amazonaws.com/public.bitmex.com/data/trade/"

XBTUSD = "XBTUSD"
ETHUSD = "ETHUSD"
XRPUSD = "XRPUSD"

uBTC = 0.000001  # 0.001 mXBT
