GOOGLE_APPLICATION_CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS"
FIREBASE_ADMIN_CREDENTIALS = "FIREBASE_ADMIN_CREDENTIALS"
FIREBASE_URL = "FIREBASE_URL"
FIRESTORE_COLLECTION = "FIRESTORE_COLLECTION"
BIGQUERY_DATASET = "BIGQUERY_DATASET"
BIGQUERY_LOCATION = "BIGQUERY_LOCATION"
BIGQUERY_TABLE_NAME = "BIGQUERY_TABLE_NAME"
PUBSUB_TOPIC = "PUBSUB_TOPIC"


GCP_APPLICATION_CREDENTIALS = (
    GOOGLE_APPLICATION_CREDENTIALS,
    FIREBASE_ADMIN_CREDENTIALS,
)

PRODUCTION_ENV_VARS = (
    BIGQUERY_LOCATION,
    BIGQUERY_DATASET,
    BIGQUERY_TABLE_NAME,
    FIRESTORE_COLLECTION,
    FIREBASE_URL,
)

BITMEX_S3 = "https://s3-eu-west-1.amazonaws.com/public.bitmex.com/data/trade/"
